### ISSUE TITLE
Describe main fuctional and non-functional reuirements

### ISSUE THREAD

**Issue by IceLark8** [Programming-Engineering-Pmi-31/StudVoice#7]
Create a file in which describe all the functionality and requirements of our project.

**Comment by NazarSamar** [comment]
[functional requirements.txt](https://github.com/Programming-Engineering-Pmi-31/StudVoice/files/3613968/functional.requirements.txt)
[Non-functional requirements.docx](https://github.com/Programming-Engineering-Pmi-31/StudVoice/files/3613969/Non-functional.requirements.docx)
Upload functional and non-functional requirements to our project.
